steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/dtu-mlops-411420/train:latest",
        "-f",
        "docker/train.dockerfile",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/dtu-mlops-411420/train:latest"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/dtu-mlops-411420/deploy:latest",
        "-f",
        "docker/deploy.dockerfile",
        "--cache-from",
        "gcr.io/dtu-mlops-411420/train:latest",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/dtu-mlops-411420/deploy:latest"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "model-deploy"
      - "--image"
      - "gcr.io/dtu-mlops-411420/deploy:latest"
      - "--region"
      - "europe-west1"
      - "cpu"
      - "2000m"
      - "memory"
      - "8Gi"
