workerPoolSpecs:
    machineSpec:
        machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
        imageUri: gcr.io/dtu-mlops-411420/train:latest
        env:
            - name: "WANDB_API_KEY"
              value: "fill me"
