# @package _global_

defaults:
  - datamodule: speechcmd
  - model: resnet50
  - predict: forward
  - _self_

seed: 42
idx_to_class: "data/processed/class_idx_export.npy"
api_port: 8001
ui_port: 8002

hydra:
  job:
    chdir: false
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./outputs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
