# @package _global_

defaults:
  - datamodule: speechcmd
  - model: resnet50
  - trainer: default
  - logger: wandb
  - _self_

run_name: null
project_name: dtu_mlops_project
seed: 42
ckpt_path: null
test: true
bucket_name: dtu_mlops_project_data
source_blob_name: data/raw/data.zip
model_blob_name: models/model_${now:%H-%M-%S}.pt

hydra:
  job:
    chdir: true
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./outputs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
