_target_: dtu_mlops_project.data.speechcmd.SpeechCommandsDataModule

data_path: data/processed/SPEECHCMD
batch_size: 32
n_workers: 6
classes: null

train_transforms:
  - _target_: torchaudio.transforms.Spectrogram
    n_fft: 512
    power: 1
  # - _target_: dtu_mlops_project.data.data_utils.RandomTimeStretch
  #   n_freq: 257
  #   rate_range: [0.9999, 1.0001]
  #   return_complex: false
  - _target_: torchaudio.transforms.FrequencyMasking
    freq_mask_param: 15
  - _target_: torchaudio.transforms.MelScale
    n_mels: 80
    sample_rate: 16000
    n_stft: 257
  - _target_: dtu_mlops_project.data.data_utils.AmplitudeToDB
    power: 2
    ref: 1.0
    top_db: 80

test_transforms:
  - _target_: torchaudio.transforms.Spectrogram
    n_fft: 512
    power: 1
  - _target_: torchaudio.transforms.MelScale
    n_mels: 80
    sample_rate: 16000
    n_stft: 257
  - _target_: dtu_mlops_project.data.data_utils.AmplitudeToDB
    power: 2
    ref: 1.0
    top_db: 80
