name: Build and Test

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Add DATA_PATH to .env file
        run: echo "DATA_PATH=$(pwd)/data/raw" >> .env

      - name: Install FFMPEG
        run: sudo apt-get install -y ffmpeg

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements_dev.txt
          pip install -e .

      - name: Run linting
        run: ruff --output-format=github .

      - name: Run tests
        run: pytest tests/ --cov-config=.coveragerc --cov=dtu_mlops_project --cov-report=xml --cov-report=html --junitxml=junit/test-results-3.11.xml

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results-3.11
          path: junit/test-results-3.11.xml
        # Publish test results even when there are test failures
        if: ${{ always() }}
